### ISSUE TITLE
QLS Overview Papers

### ISSUE THREAD

**Issue by ianmcloughlin** [fatahjamro/thesis#10]
Create a new journal article, expanding the QLS conference article into a journal article.

# QLS Overview Conference Paper

- Original repo for QLS conference paper: https://github.com/ianmcloughlin/qls_overview
- Submitted to https://ieee-qcnc.org/

# QLS Overview Journal Article
- Repo for QLS journal article: https://github.com/fatahjamro/qec-survey-ieee
- Possible submission: https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=9739

**Comment by ianmcloughlin** [comment]
Targeting end of April for new overview paper draft submission.

**Comment by fatahjamro** [comment]
Created new repo for IEEE QEC survey Journal paper in repo [qecc-lit-review](https://github.com/fatahjamro/qecc-lit-review) 
Already submitted QCNC paper, hence closing this issue.
